version: "3"

services:
  app:
    image: wap/webxiang:latest
    restart: unless-stopped
    build: .
    volumes:
        - ${RUN_DIR:-./run}:/app/run
        - app_static:/app/static
    environment:
        - VIRTUAL_HOST=${VIRTUAL_HOST:-}
        - VIRTUAL_PATH=${VIRTUAL_PATH:-/}
    depends_on:
        - memcached
  nginx:
      image: nginx:1.25
      restart: unless-stopped
      volumes:
          - app_static:/app/static
          - ${RUN_DIR:-./run}:/app/run
          - ${NGINX_DIR_TEMPLATES:-./run/nginx/templates}:/etc/nginx/templates
      ports:
          - "8080:80"
      environment:
          - VIRTUAL_HOST=${VIRTUAL_HOST:-_}
          - VIRTUAL_PATH=${VIRTUAL_PATH:-/}
      depends_on:
          - app
  memcached:
      image: memcached:1.6
      restart: unless-stopped
      entrypoint:
          - memcached
          - -m 2

volumes:
  app_static:
