services:
  app:
    image: wap/webxiang:latest
    build: .
    volumes:
        - ./run:/app/run
        - ./run/data:/app/data
    ports:
        - "8080:80"
  memcached:
      image: memcached:1.6
      entrypoint:
          - memcached
          - -m 2
