version: "3"

services:
  app:
    image: wap/webxiang:latest
    build: .
    volumes:
        - ${RUN_DIR:-./run}:/app/run
    ports:
        - "8080:80"
  memcached:
      image: memcached:1.6
      entrypoint:
          - memcached
          - -m 2
